/** Serves files from local storage in development. In production, files are served from S3/CDN. */
import { promises as fs } from "fs";
import path from "path";
import { localStorageRoot, mimeFromPath } from "@/server/storage";

export async function GET(req: Request, { params }: { params: Promise<{ key: string[] }> }) {
  const { key } = await params;
  const full = path.normalize(path.join(localStorageRoot, ...key));
  if (!full.startsWith(localStorageRoot + path.sep)) return new Response("Not found", { status: 404 });
  try {
    const data = await fs.readFile(full);
    const download = new URL(req.url).searchParams.get("download");
    const headers: Record<string, string> = {
      "Content-Type": mimeFromPath(full),
      "Cache-Control": "public, max-age=31536000, immutable",
      // SVG previews are generated by us; still lock them down.
      "Content-Security-Policy": "default-src 'none'; img-src data:; style-src 'unsafe-inline'; media-src 'self'",
      "X-Content-Type-Options": "nosniff",
    };
    if (download) headers["Content-Disposition"] = `attachment; filename="${download.replace(/[^\w.\- ]/g, "")}"`;
    return new Response(new Uint8Array(data), { headers });
  } catch {
    return new Response("Not found", { status: 404 });
  }
}
